language: php
sudo: required
env:
  global:

  matrix:

php:
  - 7.0

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

addons:
  firefox: "47.0.1"

cache:
  apt: true
  directories:
    - "node_modules"
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true

before_script:
- composer config -g github-oauth.github.com $GITHUB_TOKEN
- npm install -g gulp-cli
- composer global require hirak/prestissimo
- sudo sed -i '1s/^/127.0.0.1 localhost\n/' /etc/hosts # forcing localhost to be the 1st alias of 127.0.0.1 in /etc/hosts (https://github.com/seleniumhq/selenium/issues/2074)
- sudo apt-get update -qq
- sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi > /dev/null
- sudo mkdir $(pwd)/.run
- chmod a+x build/redCORE/tests/travis-php-fpm.sh
- sudo ./build/redCORE/tests/travis-php-fpm.sh $USER $(phpenv version-name)
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
- sudo cp -f build/redCORE/tests/travis-ci-apache.conf /etc/apache2/sites-available/default
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
- sudo sed -e "s?%PHPVERSION%?${TRAVIS_PHP_VERSION:0:1}?g" --in-place /etc/apache2/sites-available/default
- git submodule update --init --recursive
- sudo service apache2 restart
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- sudo apt-get install fluxbox -y --force-yes
- fluxbox &
- sleep 3 # give fluxbox some time to start
# Following line uses a bot account to authenticate in github and make composer stable and faster, see https://redweb.atlassian.net/wiki/pages/viewpage.action?pageId=46694753
- composer install --working-dir ./extensions/libraries/redshopb --ansi
- composer install --working-dir ./extensions/plugins/vanir_search/solr --ansi
- cd build
- npm install
- mv gulp-config.json.dist gulp-config.json
- gulp release --skip-version
- cd ../tests
# Generic RoboFile init file
- mv RoboFile.ini.dist RoboFile.ini

